import assert from 'node:assert/strict';
import test from 'node:test';
import { GenerationJobQueue, generationJobContract } from '../jobs.mjs';
const meta = (slotId, seed = 1) => ({ chatId: 'chat', messageId: 'message', swipeKey: '0', slotId, action: 'resolve', request: { text: 'private', params: { seed } } });
const deferred = () => { let resolve; const promise = new Promise(yes => { resolve = yes; }); return { promise, resolve }; };
async function waitFor(predicate) { for (let i = 0; i < 500; i++) { const value = predicate(); if (value) return value; await new Promise(resolve => setTimeout(resolve, 2)); } assert.fail('timed out'); }
test('queue defaults and contract expose required lifecycle', () => { assert.equal(generationJobContract.defaultConcurrency, 1); assert.equal(generationJobContract.retentionMs, 600_000); assert.deepEqual(generationJobContract.states, ['queued', 'resolving', 'provider-running', 'persisting', 'completed', 'failed', 'cancelled']); });
test('queue enforces global FIFO concurrency and hides sensitive metadata', async t => {
 const gates = new Map([[1, deferred()], [2, deferred()], [3, deferred()]]); const started = []; let running = 0; let maximum = 0;
 const queue = new GenerationJobQueue({ executor: async ({ request, updateState }) => { const seed = request.params.seed; started.push(seed); maximum = Math.max(maximum, ++running); updateState('provider-running'); await gates.get(seed).promise; updateState('persisting'); running--; return { seed }; } }); t.after(() => queue.close());
 const jobs = [1, 2, 3].map(seed => queue.create(seed === 2 ? 'bob' : 'alice', meta(String(seed), seed))); await waitFor(() => started.length === 1); assert.deepEqual(started, [1]); assert.equal(maximum, 1); assert.equal(Object.hasOwn(queue.get('alice', jobs[0].jobId), 'request'), false); assert.equal(Object.hasOwn(queue.get('alice', jobs[0].jobId), 'owner'), false); assert.equal(queue.get('bob', jobs[0].jobId), null);
 gates.get(1).resolve(); await waitFor(() => started.length === 2); assert.deepEqual(started, [1, 2]); gates.get(2).resolve(); await waitFor(() => started.length === 3); assert.deepEqual(started, [1, 2, 3]); gates.get(3).resolve(); await waitFor(() => jobs.every(job => queue.get(job === jobs[1] ? 'bob' : 'alice', job.jobId)?.state === 'completed'));
});
test('queued and running cancellation terminate and abort active work', async t => {
 const observed = []; const queue = new GenerationJobQueue({ executor: ({ request, signal, updateState }) => new Promise((_resolve, reject) => { observed.push(request.params.seed); updateState('provider-running'); signal.addEventListener('abort', () => reject(signal.reason), { once: true }); }) }); t.after(() => queue.close()); const running = queue.create('alice', meta('running', 1)); const queued = queue.create('alice', meta('queued', 2)); await waitFor(() => queue.get('alice', running.jobId)?.state === 'provider-running'); assert.equal(queue.cancel('alice', queued.jobId).job.state, 'cancelled'); assert.deepEqual(observed, [1]); assert.equal(queue.cancel('alice', running.jobId).job.state, 'cancelled'); await waitFor(() => queue.get('alice', running.jobId)?.state === 'cancelled'); assert.deepEqual(observed, [1]);
});
test('failures are safe and terminal records retain for ten minutes', async t => {
 let now = 1_000_000; const queue = new GenerationJobQueue({ now: () => now, executor: async () => { throw new Error('secret raw provider body'); } }); t.after(() => queue.close()); const created = queue.create('alice', meta('failed')); const failed = await waitFor(() => { const job = queue.get('alice', created.jobId); return job?.state === 'failed' && job; }); assert.deepEqual(failed.error, { code: 'generation_failed', message: 'Generation job failed' }); assert.equal(JSON.stringify(failed).includes('secret'), false); now += 599_999; assert.ok(queue.get('alice', created.jobId)); now += 1; assert.equal(queue.get('alice', created.jobId), null);
});
